-- Create product tables migration

-- Create brand table
CREATE TABLE "brand" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "slug" varchar UNIQUE NOT NULL,
  "logo_url" varchar,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

-- Create category table
CREATE TABLE "category" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "slug" varchar UNIQUE NOT NULL,
  "parent_id" bigint,
  "level" integer DEFAULT 1,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

-- Create product table
CREATE TABLE "product" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "slug" varchar UNIQUE NOT NULL,
  "description" text,
  "brand_id" bigint,
  "main_category_id" bigint,
  "is_active" boolean DEFAULT true,
  "deleted_at" timestamp DEFAULT null,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

-- Create product_sku table
CREATE TABLE "product_sku" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" bigint NOT NULL,
  "sku_code" varchar NOT NULL,
  "barcode" varchar,
  "price" decimal(12,2) NOT NULL,
  "compare_at_price" decimal(12,2),
  "weight" decimal(12,2),
  "length" decimal(12,2),
  "width" decimal(12,2),
  "height" decimal(12,2),
  "is_active" boolean DEFAULT true,
  "deleted_at" timestamp DEFAULT null,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

-- Create attribute table
CREATE TABLE "attribute" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "code" varchar NOT NULL
);

-- Create attribute_value table
CREATE TABLE "attribute_value" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "attribute_id" bigint NOT NULL,
  "value" varchar NOT NULL,
  "meta_data" jsonb
);

-- Create sku_attribute_value table
CREATE TABLE "sku_attribute_value" (
  "sku_id" bigint NOT NULL,
  "attribute_id" bigint NOT NULL,
  "attribute_value_id" bigint NOT NULL,
  PRIMARY KEY ("sku_id", "attribute_id")
);

-- Create product_category table
CREATE TABLE "product_category" (
  "product_id" bigint NOT NULL,
  "category_id" bigint NOT NULL,
  PRIMARY KEY ("product_id", "category_id")
);

-- Create product_image table
CREATE TABLE "product_image" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" bigint NOT NULL,
  "image_url" varchar NOT NULL,
  "sort_order" integer DEFAULT 0,
  "is_thumbnail" boolean DEFAULT false
);

-- Create sku_image table
CREATE TABLE "sku_image" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sku_id" bigint NOT NULL,
  "image_url" varchar NOT NULL,
  "sort_order" integer DEFAULT 0
);

-- Create product_audit_log table
CREATE TABLE "product_audit_log" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" bigint,
  "sku_id" bigint,
  "action" varchar NOT NULL,
  "performed_by" bigint,
  "old_value" jsonb,
  "new_value" jsonb,
  "created_at" timestamp DEFAULT (now())
);

-- Create product_review table
CREATE TABLE "product_review" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "rating" smallint NOT NULL,
  "comment" text,
  "is_approved" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now())
);

-- Add foreign key constraints
ALTER TABLE "product" ADD FOREIGN KEY ("main_category_id") REFERENCES "category" ("id");
ALTER TABLE "product" ADD FOREIGN KEY ("brand_id") REFERENCES "brand" ("id");

ALTER TABLE "product_sku" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id");

ALTER TABLE "product_category" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id");
ALTER TABLE "product_category" ADD FOREIGN KEY ("category_id") REFERENCES "category" ("id");

ALTER TABLE "attribute_value" ADD FOREIGN KEY ("attribute_id") REFERENCES "attribute" ("id");

ALTER TABLE "sku_attribute_value" ADD FOREIGN KEY ("sku_id") REFERENCES "product_sku" ("id");
ALTER TABLE "sku_attribute_value" ADD FOREIGN KEY ("attribute_id") REFERENCES "attribute" ("id");
ALTER TABLE "sku_attribute_value" ADD FOREIGN KEY ("attribute_value_id") REFERENCES "attribute_value" ("id");

ALTER TABLE "product_image" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id");

ALTER TABLE "sku_image" ADD FOREIGN KEY ("sku_id") REFERENCES "product_sku" ("id");

ALTER TABLE "product_review" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id");

-- Create indexes
CREATE UNIQUE INDEX "idx_product_sku_sku_code_deleted_at" ON "product_sku" ("sku_code", "deleted_at");
CREATE UNIQUE INDEX "idx_product_sku_barcode" ON "product_sku" ("barcode");

-- Add comments
COMMENT ON COLUMN "product"."slug" IS 'URL friendly, cần đánh index';
COMMENT ON COLUMN "product"."main_category_id" IS 'Danh mục chính để breadcrumb/sort';
COMMENT ON COLUMN "attribute_value"."meta_data" IS 'Lưu mã màu Hex, hoặc tên hiển thị khác nếu cần';
COMMENT ON COLUMN "product_audit_log"."performed_by" IS 'Admin User ID';

